### PR TITLE
Adding badges

### PR DESCRIPTION
**Pull request by d1vious**
Adds badges to README.md for the CI job [yaml-linting](https://github.com/LOLBAS-Project/LOLBAS/blob/master/.github/workflows/yaml-linting.yml) and a script (`scripts/lolbas_count.py`) to calculate the lolbas count that generates the [svg badge](https://lolbas-project.s3.us-east-2.amazonaws.com/lolbas_count.svg), right now I uploaded it to a public s3 bucket
 
It can easily be automatically updated via a scheduled GitHub action with creds to push to that bucket, happy to share.

image

### CODE REVIEW

**Comment by xenoscr** [comment]
@d1vious can you add "indent=2" and "explicit_start=True" to your yaml.dump calls to ensure that the indenting doesn't change and that the document start ("---") is present at the top of each YAML file? I think making those changes should fix some of the conflicts?

**Comment by xenoscr** [comment]
@d1vious if those changes don't do it, you may need to re-sync your fork and apply your changes maybe?

**Comment by xenoscr** [comment]
@d1vious, I have been thinking and looking around, there may be a way to make this a workflow action. The workflow would perform the following actions:

1. Checkout Action
2. [Setup Python](https://github.com/marketplace/actions/setup-python) (See the section about dependencies, it can install any requirements as well)
3. Run your script, placing the SVG in a specific folder in the repo.
4. Use a "run" step to add & commit the new SVG (StackOverflow [Example](https://stackoverflow.com/a/58393457))

This would ensure that the badge is regenerated for each pull request and keep the file local to our repo.

**Comment by d1vious** [comment]
> @d1vious if those changes don't do it, you may need to re-sync your fork and apply your changes maybe?

Yeah just realized my fork was out of date, let me get that fix!

**Comment by d1vious** [comment]
closing this one since I made a branch of the project instead of my fork https://github.com/LOLBAS-Project/LOLBAS/pull/256

**Pull request closed without merging**
