### PR TITLE
Update MpCmdRun.yml

### PR DESCRIPTION
**Pull request by richrumble**
Added note that slashes (/) can also be used as command separators, and that the UA is MpCommunication
Thanks!

### CODE REVIEW

**Review by xenoscr — CHANGES_REQUESTED** [review]
@richrumble the "Note" field is not part of the template format: https://github.com/LOLBAS-Project/LOLBAS/blob/master/YML-Template.yml

You're example can be entered as a new example. Also, feel free to give yourself some acknowledgement for the contributions.

**Comment by xenoscr** [comment]
@richrumble, I requested a few changes. Please make the appropriate updates and I will merge your pull request if everything looks good.

**Review by richrumble — COMMENTED** [review]
Submitted changes

**Review by xenoscr — APPROVED** [review]
Thank you for removing the "Note" entry and providing more context on the alternate slashes.

**Review by xenoscr — APPROVED** [review]
Great IOC addition, thank you.

**Pull request merged**
