### PR TITLE
Create Wsl.yml

### PR DESCRIPTION
**Pull request by NotoriousRebel**
With WSL 2 it will only be more prevalent.

### CODE REVIEW

**Comment by api0cradle** [comment]
Awesome find. Do you know if WSL.exe is default added in the latest Windows 10? If it is not present default we need to move this to OtherMSBinaries.

**Comment by api0cradle** [comment]
Verified that it is not enabled by default, will move this to otherMSBinaries.

**Comment by NotoriousRebel** [comment]
@api0cradle The user has to install it, I put it in OSBinaries because bash was in there, my bad.
Also added a neat example of running commands as root without being prompted for password.

**Comment by api0cradle** [comment]
Thanks. Great addition! 👍

**Comment by api0cradle** [comment]
https://lolbas-project.github.io/lolbas/OtherMSBinaries/Wsl/

**Pull request merged**
