### PR TITLE
dsdbutil.exe

### PR DESCRIPTION
**Pull request by Ekitji**
LOLBIN for dumping NTDS

### CODE REVIEW

**Review by josehelps — APPROVED** [review]
LGTM, command checks out!

**Comment by josehelps** [comment]
@Ekitji looks like yaml ran into some linting issues, mind taking a peak: https://github.com/LOLBAS-Project/LOLBAS/actions/runs/5205194428/jobs/9458135237?pr=292

**Comment by Ekitji** [comment]
seriously how hard can it be to get the new line ending correct.............. tried in vs studio code with unix format and also.. tried to do it in a linux machine.. still not accepting it..

**Comment by josehelps** [comment]
@Ekitji that was a effort, I super happy it seems like you got it :tada: thank you so much again for fighting with it happy to finally approve and merge :raised_hands:

**Pull request merged**
