### PR TITLE
Create register_app.yml

### PR DESCRIPTION
**Pull request by esebese**

### CODE REVIEW

**Comment by wietze** [comment]
Thanks for opening this PR, I like your find. 

I could locate the file in Windows 10 SDK 10.0.19041.0, however, it does not appear to be signed, as opposed to the other .vbs LOLScripts currently in LOLBAS:

image

This submission would therefore not meet the [criteria](https://github.com/LOLBAS-Project/LOLBAS#criteria) as currently defined. 

(Also, we currently only have a `OSScripts` category whereas this one would technically class as `OtherMSScripts` since it comes with the Windows SDK)

**Review by wietze — COMMENTED** [review]
Thanks for opening this PR, I like your find!

I could locate the file in Windows 10 SDK 10.0.19041.0, however, it does not appear to be signed, as opposed to the other .vbs LOLScripts currently in LOLBAS:

image

This submission would therefore not meet the [criteria](https://github.com/LOLBAS-Project/LOLBAS#criteria) as currently defined. 

(Also, we currently only have a `OSScripts` category whereas this one would technically class as `OtherMSScripts` since it comes with the Windows SDK)

**Comment by esebese** [comment]
Thank you for the detailed explanation. 

You are absolutely right about the meeting criteria. My motivation to create this PR was similar to your idea, finding a gun in an island that has no serial number, however you can still operate it. Also, it has been around for 20 years, maybe it would help community to scan their system and to be aware of upcoming utilization. 

Do you want me to close this PR and open under OtherMSScripts class?

**Comment by xenoscr** [comment]
Thank you @esebese for your submission. Apologies for the delay in this but, as @wietze mentioned, this does not meet the [criteria](https://github.com/LOLBAS-Project/LOLBAS#criteria) for the LOLBas so we are closing this pull request. This was still an interesting find.

**Pull request closed without merging**
