### PR TITLE
ATT&CK realignment, typo fixes

### PR DESCRIPTION
**Pull request by akat12**
Pnputil: T1547.006 is the wrong tid as it's only applicable to Linux and MacOS. The more appropriate tid would be T1547.008.
Msxsl: fixed some command spellings.

### CODE REVIEW

**Review by wietze — COMMENTED** [review]
Good spot! 
This is a bit of a tricky one as I don't think 'Lsass Driver' is the right one either (to be honest, this subtechnique has always confused me). 
What do you think about changing it to the more generic `T1547` instead? Not ideal either, but there doesn't seem to be a good fit for anything that relies on 'traditional' drivers...

**Comment by akat12** [comment]
True enough. I think T1547 is the best solution for now as well.

**Review by wietze — APPROVED** [review]
Great work, thanks for your contribution!

**Comment by akat12** [comment]
@wietze I think T1014 Rootkit would be a better fit.  What do you think? 

[T1014](https://attack.mitre.org/techniques/T1014/)

**Comment by wietze** [comment]
Good suggestion, it is a really tricky one! This is the response I got from the kind people of ATT&CK:
image

**Pull request merged**
