### PR TITLE
Update eventvwr.yml with Execute part

### PR DESCRIPTION
**Pull request by Kucharskov**
All things added based on https://twitter.com/orange_8361/status/1518970259868626944 and my re-tests.

### CODE REVIEW

**Comment by bohops** [comment]
This functionality works with my testing.
It doesn't look like I can make changes to the contents of the PR. @Kucharskov would you mind adding an acknowledgment for Orange Tsai and changing the 'Privileges' from User to Administrator?

**Comment by Kucharskov** [comment]
I really forgot about that PR. Could you check @bohops if my changes is fine? Otherwise just tell me what i need to also change.
Thanks in advance!

**Comment by bohops** [comment]
@Kucharskov thank you for updating the PR! Just one more request - can you add a newline at the end of the yaml file?

The lint check threw the following error:

image

**Comment by Kucharskov** [comment]
Maybe now?

**Comment by bohops** [comment]
Looks good! Thank you for contributing!

**Pull request merged**
