### PR TITLE
Added colorcpl.exe

### PR DESCRIPTION
**Pull request by ArjanOnwezen**
Added colorcpl.exe

### CODE REVIEW

**Comment by wietze** [comment]
For reference - this entry is also included in #189 which is still under review

**Comment by ArjanOnwezen** [comment]
@wietze  oops wasn't aware of that one. 
Just checked main website and noticed colorcpl.exe was missing. 
A SANS blogpost mentioned colorcpl was used, hence I created the PR
https://isc.sans.edu/diary/Guildma+is+now+abusing+colorcplexe+LOLBIN/29814
Any clue why colorcpl hasn't been added yet (looks like the PR is over a year old)?

**Comment by ArjanOnwezen** [comment]
@wietze lookslike something went wrong with the merge
https://github.com/LOLBAS-Project/LOLBAS/compare/00c07a65f344ffff9ce77e13ffa0de50143b5002..fa3f6bbc0c9fd71330c57385d44023c2aebebbf3

**Comment by wietze** [comment]
Thanks for pointing this out, no idea what happened here! Will see if I can fix it

**Comment by ArjanOnwezen** [comment]
@wietze thanks and what a nice project!

**Pull request merged**
