### PR TITLE
Create AccCheckConsole.yml

### PR DESCRIPTION
**Pull request by bohops**
AccCheckConsole.exe is a Microsoft signed binary from the SDK that allows an arbitrary managed DLL to be loaded (that fits the verification structure).

### CODE REVIEW

**Review by wietze — CHANGES_REQUESTED** [review]
Great new technique - good find! 
Is it worth discussing the significance of `-window "Untitled - Notepad"` and/or its reliance on there being an open `notepad.exe` instance? Other than that, looks good to me

**Comment by bohops** [comment]
There is no particular reliance on Notepad, but rather an active Window title. Notepad was just the easiest to replicate but anything else should work as well :)

**Comment by wietze** [comment]
nice one, that's what I suspected - might be worth adding to the entry itself (`description` fields maybe?) as it might not be entirely clear if you haven't read the tweets

**Review by wietze — APPROVED** [review]
Thanks @bohops , will merge this now!

**Pull request merged**
